version: '2'
services:
  database:
    image: "mongo"
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
        - ./data:/data/db
        
  backend:
    build: ./backend/
    restart: always
    environment:
      - MONGO_DB_URI=mongodb://database
    volumes :
      - /app/node_modules/
    depends_on:
      - database
      
  frontend:
    build: ./frontend/
    restart: always
    ports:
      - "3000:3000"
    volumes:
      - /app/node_modules/
    depends_on:
      - backend